spring.application.name=api-sus-estrangeiros

# Diz para o Spring usar o banco H2 em memória com o nome "susdb"
spring.datasource.url=jdbc:h2:mem:susdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Mágica do JPA: Cria as tabelas no banco automaticamente baseadas no seu código
spring.jpa.hibernate.ddl-auto=update

server.port=8081