spring.application.name=api-sus-estrangeiros

# Configurações do Banco de Dados H2
spring.datasource.url=jdbc:h2:mem:susdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar o console do H2 para visualização (acesso em /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Cria as tabelas automaticamente baseadas no código
spring.jpa.hibernate.ddl-auto=update

# Mostra as queries SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081